//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniformRenamer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Textual {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Textual() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniformRenamer.Textual", typeof(Textual).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination tag.
        /// </summary>
        internal static string DestinationTag {
            get {
                return ResourceManager.GetString("DestinationTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give a tag to this rule, and the copied/replaced text will be inserted to where this tag appears in the &apos;New Format&apos; textbox..
        /// </summary>
        internal static string DestinationTagTooltip {
            get {
                return ResourceManager.GetString("DestinationTagTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete rule empty.
        /// </summary>
        internal static string ErrorDeleteRule {
            get {
                return ResourceManager.GetString("ErrorDeleteRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two items have the same new name, therefore renaming is canceled.
        /// </summary>
        internal static string ErrorDuplicateNewName {
            get {
                return ResourceManager.GetString("ErrorDuplicateNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already exists, therefore renaming is stopped..
        /// </summary>
        internal static string ErrorFileExists {
            get {
                return ResourceManager.GetString("ErrorFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace rules need to have at least 3 items delimited by tabs.
        /// </summary>
        internal static string ErrorReplaceRule {
            get {
                return ResourceManager.GetString("ErrorReplaceRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Loaded.
        /// </summary>
        internal static string FileLoaded {
            get {
                return ResourceManager.GetString("FileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Saved.
        /// </summary>
        internal static string FileSaved {
            get {
                return ResourceManager.GetString("FileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Copy Rule.
        /// </summary>
        internal static string InsertCopyRule {
            get {
                return ResourceManager.GetString("InsertCopyRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Delete Rule.
        /// </summary>
        internal static string InsertDeleteRule {
            get {
                return ResourceManager.GetString("InsertDeleteRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Replace Rule.
        /// </summary>
        internal static string InsertReplaceRule {
            get {
                return ResourceManager.GetString("InsertReplaceRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File Name Preview.
        /// </summary>
        internal static string NewFileName {
            get {
                return ResourceManager.GetString("NewFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Rule.
        /// </summary>
        internal static string RemoveRule {
            get {
                return ResourceManager.GetString("RemoveRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please doublecheck the renaming preview. Do you wish to continue the renaming process?.
        /// </summary>
        internal static string RenameWarning {
            get {
                return ResourceManager.GetString("RenameWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement text.
        /// </summary>
        internal static string ReplacementText {
            get {
                return ResourceManager.GetString("ReplacementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Type.
        /// </summary>
        internal static string RuleType {
            get {
                return ResourceManager.GetString("RuleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target search patterns (separated by tab, &apos;* &apos; denotes a regular expression).
        /// </summary>
        internal static string SearchPatterns {
            get {
                return ResourceManager.GetString("SearchPatterns", resourceCulture);
            }
        }
    }
}
